# Generated by Django 5.0.1 on 2024-02-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="ad", old_name="renk", new_name="rank",),
    ]
