# Generated by Django 5.0.1 on 2024-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_renk_ad_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "new"),
                    ("hot", "hot"),
                    ("sale", "sale"),
                    ("", "default"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.CharField(
                blank=True,
                choices=[("In Stock", "In Stock"), ("Out of Stock", "Out of Stock")],
                max_length=25,
            ),
        ),
    ]
